version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
  mcp-server:
    image: dadosfera/mcp-server
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=us-east-1
      - DADOSFERA_USERNAME=$DADOSFERA_USERNAME
      - DADOSFERA_PASSWORD=$DADOSFERA_PASSWORD

volumes:
  postgres_data:
    driver: local 